"""Cat Class

Revision ID: 23372cf8e850
Revises: e5f933669a40
Create Date: 2024-04-28 19:34:36.960047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23372cf8e850'
down_revision = 'e5f933669a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('breed',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('adoption_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.alter_column('adoption_fee',
               existing_type=sa.String(length=100),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('color',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('age',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('breed',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
